version: '3'

services:
  doctors:
    image: ahmedyaar/doctors:${DOCTORS_TAG:-latest}
    ports:
      - "9090:9090"
    networks:
      - microservices-network

  appointments:
    image: ahmedyaar/appointments:${APPOINTMENTS_TAG:-latest}
    ports:
      - "7070:7070"
    networks:
      - microservices-network

  frontend:
    image: ahmedyaar/frontend:${FRONTEND_TAG:-latest}
    ports:
      - "3000:3000"
    networks:
      - microservices-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: appointments_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3307:3306"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
