apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:

  replicas: 3
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors

    # BONUS PART 2       
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000

      initContainers:
      - name: init-container
        image: ubuntu:20.04
        command: ['sh', '-c', 'echo "My name is Ahmed Yar" && sleep 5']




    spec:
      containers:
      - name: doctors
        image: ahmedyaar/microservice-doctors:1.0.0
        # Bonus Part
        volumeMounts:
        - name: details-volume
          mountPath: /user/details.txt

        ports:
        - containerPort: 9090
        env:
        - name: DOCTORS_DB_HOST
          value: doctors-db-service

        # Phase 4
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

      volumes:
      - name: details-volume
        configMap:
          name: doctors-config

---
apiVersion: v1
kind: Service
metadata:
  name: doctors-service
spec:
  selector:
    app: doctors
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
